camera_index: 0
confidence_threshold: 0.5
target_species: ["deer", "wild_boar", "elephant"]
alert_methods: ["buzzer", "light", "email", "sms"]
wildlife_insights_api_key: "YOUR_API_KEY"
notification:
  sms:
    enabled: true
    twilio_sid: "YOUR_TWILIO_SID"
    twilio_token: "YOUR_TWILIO_TOKEN"
    from: "+123456789"
    to: "+987654321"
  email:
    enabled: true
    from: "your@email.com"
    to: "alert@email.com"
    smtp_server: "smtp.example.com"
    smtp_port: 587
    smtp_user: "your@email.com"
    smtp_password: "your_password"